import { APP_NAME } from "@/common/constants";
import About from "@/module/About";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: `Home - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
};

const AboutPage = () => {
  return <About/>;
};

export default AboutPage;
