import { APP_NAME } from "@/common/constants";
import Blog from "@/module/Blog";
import Cta from "@/module/Home/Cta";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: `Home - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
};

const HomePage = () => {
  return (
    <div>
      <Blog />
      <Cta/>
    </div>
  );
};

export default HomePage;
