import Cta from "@/common/components/Layout/Cta";
import { WidthWrapper } from "@/common/components/WidthWrapper";
import { APP_NAME } from "@/common/constants";
import Blog from "@/module/Blog";
import Banner from "@/module/Blog/Banner";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: `Home - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
};

const BlogPage = () => {
  return (
    <div>
      <Banner />
      <WidthWrapper width="medium">
        <Blog />
      </WidthWrapper>

      <Cta />
    </div>
  );
};

export default BlogPage;
