import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css"
import Cta from "@/module/Home/Cta";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className={inter.className}>
        {children}
        <Cta />
      </div>
    </>
  );
}
