import { APP_NAME } from "@/common/constants";
import ContactUsSection from "@/module/Contact/ContactUsSection";
import GetInTouchWithUsSection from "@/module/Contact/GetInTouchWithUsSection";
import MapSection from "@/module/Contact/MapSection";
import MoreInformationSection from "@/module/Contact/MoreInformationSection";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: `Home - ${APP_NAME}`,
  description: `Generated by ${APP_NAME}`,
};

const ContactPage = () => {
  return (
    <div>
      <ContactUsSection />
      <div className="md:flex">
        <div className="w-1/2">
          <GetInTouchWithUsSection />
        </div>
        <div className="flex-none">
          <MoreInformationSection />
        </div>
      </div>
        {/* <MapSection /> */}
    </div>
  );
};

export default ContactPage;
